# OftW pre-giving-tuesday-email upselling split test (impact vs emotion'

## The trial

In December 2021, OftW  sent out a sequence of emails to existing OftW pledgers/participants asking them for an additional donation. There were two 'treatment variants'; an emotional email and a standard impact-based email. The treatment was constant by individual (the same person always got emails with the same theme.


The details are presented in our (currently private) gitbook [HERE](https://app.gitbook.com/o/-MfFk4CTSGwVOPkwnRgx/s/-Mf8cHxdwePMZXRTKnEE/contexts-and-environments-for-testing/one-for-the-world/pre-giving-tuesday-email-split-test) and in the linked pre-registration (also on OSF).

## Capturing data

...

(This is gitignored so it won't be 'committed' to our repo, at least for now)

Quick note here on how Kennan put the (different types of) data together in that Gsheet. We probably should use the api tool to import it directly here.


## Input and clean data


Using the API tool to grab data from Gsheet...

...

Labeling and cleaning (and make a codebook?)


## Descriptives and exploratory analysis

## Basic tests: Donation incidence and amounts

(See preregistration -- go through preregistered tests one at a time)

## Basic tests: Clicks and retention outcomes

## "Equivalence testing" with randomization inference/simulation

(Reprise/merge in analysis done [HERE](https://rethinkpriorities.github.io/methodology-statistics-design/inference-and-rough-equivalence-testing-with-binomial-outcomes.html#how-likely-are-proportions-this-similar-under-different-size-true-effect-sizes))

